name: Credit Card Transaction Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        cd DATA-5000/credit-card-anomaly
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run analysis
      run: |
        cd DATA-5000/credit-card-anomaly
        python src/main.py
    
    - name: Upload analysis results
      uses: actions/upload-artifact@v2
      with:
        name: analysis-results
        path: DATA-5000/credit-card-anomaly/transaction_analysis_output/